### ISSUE TITLE
Verify serialization methods exception

### ISSUE THREAD

**Issue by stefanomerotta** [modernuo/ModernUO#1032]
```cs
private static void VerifySerialization(Assembly assembly)
        {
            if (assembly != null)
            {
                Parallel.ForEach(assembly.GetTypes(), VerifyType);
            }
        }
```

The serialization verification is multithread but inside the **VerifyType** method a ValueStringBuilder is instantiated: it uses the single thread array pool that could causes exceptions if multiple assemblies are checked.

```cs
public ValueStringBuilder(int initialCapacity)
    {
        _arrayToReturnToPool = STArrayPool<char>.Shared.Rent(initialCapacity);
        _chars = _arrayToReturnToPool;
        _length = 0;
    }
```

We could use the standard StringBuilder in this scenario, as it is executed only in startup phase and additional memory allocation is not a problem, or add to ValueStringBuilder an option to select which pool it should use.

**Comment by kamronbatman** [comment]
Great find! I added an `_mt` to other structures. Let's do that for ValueStringBuilder. This will fall back to the regular ArrayPool which supports multiple threads via Interlock and a Monitor.

@stefanomerotta do you want to make a PR or would you like me to handle this?
