### ISSUE TITLE
Use EnumGenerators for enums

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#1048]
In some places we need to do Enum.ToString(), Enum.TryParse, or other methods. These can be replaced with their fast counterparts using a [source generator](https://github.com/andrewlock/NetEscapades.EnumGenerators).

**Comment by fabrizioiacobucci** [comment]
I was having a look to the EnumGenerators package linked there.
As I understand it generates a class with faster helper functions for each Enum with attribute [EnumExtensions].

But how would it work in generic cases like the following?

`public static T GetOrUpdateSetting<T>(string key, T defaultValue) where T : struct, Enum
    {
        T value;

        if (m_Settings.Settings.TryGetValue(key, out var strValue))
        {
            value = Enum.TryParse(strValue, out value) ? value : defaultValue;
        }
        else
        {
            SetSetting(key, (value = defaultValue).ToString());
        }

        return value;
    }`
    
Even if helper functions are generated as Static they compare the input value with the specific attributed Enum values:

E.g. "IsDefined"

`internal static partial class ColourExtensions
    public static bool IsDefined(Colour value)
        => value switch
        {
            Colour.Red => true,
            Colour.Blue => true,
            _ => false,
        };
`

**Comment by kamronbatman** [comment]
I don't see a big need for this. When we do, we can implement it.

**Comment by stefanomerotta** [comment]
In .NET8 enum methods have been rewritten and now are generic, so it could be sufficient to use the standard framework methods, as reported in this closed issue https://github.com/dotnet/runtime/pull/78580
