### ISSUE TITLE
Update LabelTo and SendMessage to Interpolated Strings

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#1053]

**Comment by fabrizioiacobucci** [comment]
I'm working on this.

**Comment by fabrizioiacobucci** [comment]
There is also ```CommandLogging.WriteLine``` using string arguments concatenation

**Comment by fabrizioiacobucci** [comment]
@kamronbatman I fixed the calls and removed the method declarations not anymore referenced. If you want, you can allow me to collaborate, so I can push the dedicated branch and you can review.

**Comment by kamronbatman** [comment]
For now, can you make a fork and a PR?

**Comment by fabrizioiacobucci** [comment]
Done. 
I feel like falling down from the sky into the project. I hope this is fine so far, I have some time to spare and willing to cotribute.
Pushing branches on the fork and pull requests is fine of course.
Thanks

**Comment by kamronbatman** [comment]
Thank you! Once you contribute regularly (a few PRs or helping to fix bugs), I'll be happy to add you and request licenses.
