### ISSUE TITLE
Change all public List/HashSet/Dictionary to ReadOnly

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#1130]
Some publicly exposed properties like Mobile.StatMobs should be ReadOnly. Let's change them to IReadOnly equiv by casting. This is only superficial but should prevent misuse.

**Comment by stefanomerotta** [comment]
If you cast them to IReadOnly* equivalent, don't you incurr into enumeration allocation? 
If I remember well, IReadOnly* interfaces don't expose the real struct enumerator but the more generic IEnumerator interface that requires boxing.
