### ISSUE TITLE
Admin Account but no Admin rights

### ISSUE THREAD

**Issue by Valdur5** [modernuo/ModernUO#1147]
Hi, I just started a new Server and used the function to automatically create an admin account.
Now I have created a char and when I use **[helpinfo** it limites me to functions which are not for admins or game mods.
How can I set myself to admin? I would have looked in the wiki but it is down (not working) and I can't find any other sources. So not sure that is a bug or a missuse of the system.

**Comment by Valdur5** [comment]
I did not understand that this is just for informational porpous ... when I enter the displayed commands it works. So I close this ticket.

**Comment by kamronbatman** [comment]
@Valdur5 I think it is valid that maybe we need a more robust command interface in general. Feel free to make an issue ticket asking for that. If possible, I would love gump studio mockups for how it should look.
