### ISSUE TITLE
Getting an error when compiling

### ISSUE THREAD

**Issue by jburns1971** [modernuo/ModernUO#1156]
Getting this error:
CSC : error CS8032: An instance of analyzer ModernUO.Serialization.Generator.EntitySerializationGenerator cannot be created from /root/.nuget/packages/modernuo.serialization.generator/2.1.4/analyzers/dotnet/cs/ModernUO.Serialization.Generator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/jburns/ModernUO/Projects/Server/Server.csproj]

I installed nuget, that didn't help. Any idea?

**Comment by kamronbatman** [comment]
This means you are not using the newest version Visual Studio 2022, or .NET 6. Update to the newest and let me know if it happens again. Also try running` publish.cmd` and tell me if that gives you the same error.

**Comment by jburns1971** [comment]
Sorry, rookie mistake. Running Ubuntu 20.04 LTS Command Line only. But I get what you are saying.

**Comment by kamronbatman** [comment]
They can run them, but most likely will require changes. A few things to consider:
- ModernUO is based on RunUO, so it lacks most of the added content from ServUO.
- ModernUO updated the API in some areas, like `BeginAction(typeof(T))` is now `BeginAction<T>()`.
- As for XMLSpawner, I started converting it, but I haven't found the time to finish. It is a massive project.

Feel free to ask questions and get support in discord. And one final note, `publish.cmd` does work in linux, and you can run `publish.sh` if you want (it just runs the cmd anyways). The publish command not only publishes ModernUO to a distribution folder, but it also runs the serialization schema generator so you can commit changes for the new source generation system (if you use it).
