### ISSUE TITLE
Tormented Minotaur unexpectedly occupy null map

### ISSUE THREAD

**Issue by mark1145** [modernuo/ModernUO#1401]
Tormented Minotaur slowly accumulate in a null map, seemingly always in increments of 4. Meraktus is an ML champ with an ability to create 4 at a time, but these null mappers are being created when Meraktus doesn't exist.

https://github.com/modernuo/ModernUO/blob/main/Projects/UOContent/Mobiles/Monsters/ML/Special/Meraktus.cs#L212

They have correct STR/DEX/INT HP etc. so presumably they are being created via their none-deserialize constructor. Looking at the created dates, it's possible they match when manually [save or when restarting the server, but I can't recall exactly so cannot confirm for sure.

I'll add some extra logging around them and try to track down what's making them

![image](https://user-images.githubusercontent.com/15312181/236100314-e97581b4-d095-4809-80f2-92724350ca72.png)

**Comment by kamronbatman** [comment]
Fixed in #1404
