### ISSUE TITLE
limit new haven to pub 16 

### ISSUE THREAD

**Issue by gnai-creator** [modernuo/ModernUO#1408]
Creating a character on a pre Renaissance server take it to haven.

**Comment by mdodkins** [comment]
I could pick this up... have my head in all this code already 🙂

**Comment by kamronbatman** [comment]
Yeah go for it, thanks!

**Comment by kamronbatman** [comment]
@mdodkins was this fixed with your available maps changes?
With that said, I see a `Core.ML` check here: 
https://github.com/modernuo/ModernUO/blob/a9a2a899083836802226b0a87e4d3197d9ecd4a8/Projects/UOContent/Misc/CharacterCreation.cs#L225-L228

So not sure how to reproduce this problem.
