### ISSUE TITLE
Monster statuette owner message when not in a house

### ISSUE THREAD

**Issue by vexyl** [modernuo/ModernUO#1417]
When attempting to activate a monster statuette when you're not in a house you get the system message "You must be the owner to use this."

MonsterStatuette.cs:
```cs
        public bool IsOwner(Mobile mob) => BaseHouse.FindHouseAt(this)?.IsOwner(mob) == true;

        public override void OnDoubleClick(Mobile from)
        {
            if (IsOwner(from))
            {
                var onOffGump = new OnOffGump(this);
                from.SendGump(onOffGump);
            }
            else
            {
                from.SendLocalizedMessage(502691); // You must be the owner to use this.
            }
        }
```
It's only checking if the player is an owner, and not 2 separate checks if they are in a house and if they are the owner of that house.

**Comment by kamronbatman** [comment]
This isn't meant to be used outside of a house. So the next question is, should we modify it so GMs can place them anywhere, and suppress player manipulation failure messages?
