### ISSUE TITLE
[Bug] Subsequent executions of the publish script result in errors

### ISSUE THREAD

**Issue by thecatontheflat** [modernuo/ModernUO#1483]
1. Create a build with `publish.sh`
2. Run this command again
3. It outputs the following errors:

![image](https://github.com/modernuo/ModernUO/assets/727581/7d63f10e-d284-4908-a83d-36935f52ad3f)

Restoring the Distribution folder doesn't help
Restoring the Projects folder helps

**Comment by kamronbatman** [comment]
Usually that error happens when there is a dotnet Nuget issue. Try clearing all Nuget caches.

**Comment by thecatontheflat** [comment]
Cannot reproduce it consistently, closing
