### ISSUE TITLE
Configurable skill/stat gain factor?

### ISSUE THREAD

**Issue by thecatontheflat** [modernuo/ModernUO#1486]
I want to run a test server with accelerated skills and stats gain.
Currently I have 2 options when it comes to skill gain:

- Either modify it in the [skills.json](https://github.com/modernuo/ModernUO/blob/main/Distribution/Data/skills.json#L13) for each skill
- Or modify it directly in the [SkillCheck.cs](https://github.com/modernuo/ModernUO/blob/main/Projects/UOContent/Skills/SkillCheck.cs#L109) logic

For a better modularity, I thought it would make sense to make this configurable.

Would you accept a PR with such a change?

**Comment by kamronbatman** [comment]
Yeah I agree.

**Comment by thecatontheflat** [comment]
@kamronbatman While refactoring this, I figured that some skills should allow for multiple stat gains, e.g.:
https://github.com/modernuo/ModernUO/blob/main/Distribution/Data/skills.json#L24-L26

While in the current implementation it seems that Str always takes priority and the rest of the logic is not executed if Str increase rolls a success:
https://github.com/modernuo/ModernUO/blob/main/Projects/UOContent/Skills/SkillCheck.cs#L245-L256

Is this intended behavior? If not, I'll change it to separate "if" statements so they all get evaluated (unless `XXXGain` is 0)

**Comment by kamronbatman** [comment]
Note that they are not `else-if` and it does not return, So it actually tries to gain each one, every time.

**Comment by thecatontheflat** [comment]
Could you please help me understand it?

From what I see, the logic is triggered once - e.g. `PlayerMobile` succeeded at using `Meditation`, which then triggers `m.CheckSkill`, which then triggers `SkillCheckLocationHandler` etc. until we get to that `else-if` block which will short-circuit on the first successful roll.

Unless you're referring to the inlined code block which was a suggestion for the future implementation

**Comment by kamronbatman** [comment]
So going back through the code it looks like it was done like this on purpose so you only gain 1 stat per skill check. Not sure if that is how OSI does it, but I imagine we need to be careful that we don't gain too many stats at once and go over a cap?

Let's discuss this more in Discord and try to find out the proper logic since I am not 💯 sure.

**Comment by kamronbatman** [comment]
Implemented.
