### ISSUE TITLE
Investigate appropriate use of death status packets

### ISSUE THREAD

**Issue by eryon** [modernuo/ModernUO#1502]
In Server/Mobile.cs, it's possible we are misusing the death status packet for players.  In `OnDeath()`, we send `DeathStatus(true)` to indicate the mobile has died, then do the event and associated logic, and immediately send another `DeathStatus` but this time with `false` to indicate... not dead?  Even though the mobile is still dead.
https://github.com/modernuo/ModernUO/blob/856db6a64c466a56966dccc8eb3b9163a48b0a47/Projects/Server/Mobiles/Mobile.cs#L4848

Then, in `Resurrect()`, we send the incoming packet twice.  I _think_ we should only send it once and send `DeathStatus(false)` here, instead.
https://github.com/modernuo/ModernUO/blob/856db6a64c466a56966dccc8eb3b9163a48b0a47/Projects/Server/Mobiles/Mobile.cs#L4528-L4529

This issue exists in ServUO and RunUO, as well:
https://github.com/ServUO/ServUO/blob/b77438329e26da390650b531d804a4a14309da1f/Server/Mobile.cs#L3963
https://github.com/ServUO/ServUO/blob/b77438329e26da390650b531d804a4a14309da1f/Server/Mobile.cs#L3446-L3447

ClassicUO seems to expect only one `DeathStatus` on death, as it responds with turning off warmode, etc.  I found this issue when I noticed CUO was sending duplicate warmode packets on death.
https://github.com/ClassicUO/ClassicUO/blob/b3468bb87d37f414f1360c4e430a7c8ba827cf73/src/ClassicUO.Client/Network/PacketHandlers.cs#L1693

**Comment by kamronbatman** [comment]
So I did some investigation, and it looks like the value `0` used to indicate that the player is dead and `2` indicated the player is a ghost. This was replaced a very long time ago with body 0x192/0x193.

I'll clean it up.
