### ISSUE TITLE
Gump refactor for caching and functional generation

### ISSUE THREAD

**Issue by stefanomerotta** [modernuo/ModernUO#1640]
This issue aims to track the conversion of gump generation to reduce object and string allocations and allow caching for gumps with static content.

Ongoing development is on dedicated branch:

**Comment by stefanomerotta** [comment]
@kamronbatman first benchmark tests on dynamic gump vs old gump:

![image](https://github.com/modernuo/ModernUO/assets/97297186/b83253e4-c192-4ffb-9d39-626afd89012b)

Benchmarks are in an ad-hoc branch: https://github.com/modernuo/ModernUO-Benchmarks/commit/a5da66ed79161c82c101aaeb7ca1d366fa9f3c2e

**Comment by kamronbatman** [comment]
That is amazing!!

**Comment by stefanomerotta** [comment]
This implementation is ready for merge: could you check the code?

**Comment by stefanomerotta** [comment]
Do we have to cancel this development due to a different roadmap?

**Comment by kamronbatman** [comment]
No, let's continue this. I am sorry I haven't found the time to work on this with you yet.

**Comment by kamronbatman** [comment]
Note: The original benchmarks didn't create the packet itself. Since the new gump technique doesn't create the gump in the constructor, we can't just test that. We have to test creating the packet (but not sending). So here is a more fair benchmark against the newest code:

```cs
BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3447/23H2/2023Update/SunValley3)
12th Gen Intel Core i9-12900K, 1 CPU, 24 logical and 16 physical cores
.NET SDK 8.0.204
  [Host]     : .NET 8.0.4 (8.0.424.16909), X64 RyuJIT AVX2
  Job-ZSGFLZ : .NET 8.0.4 (8.0.424.16909), X64 RyuJIT AVX2

Runtime=.NET 8.0  IterationCount=30  WarmupCount=30

| Method               | Mean     | Error    | StdDev   | Median   | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|--------------------- |---------:|---------:|---------:|---------:|------:|--------:|-------:|----------:|------------:|
| LegacyGump           | 22.65 us | 0.628 us | 0.921 us | 22.99 us |  1.00 |    0.00 | 0.7935 |   12496 B |       1.000 |
| NewDynamicLayoutGump | 18.33 us | 0.753 us | 1.128 us | 18.94 us |  0.81 |    0.04 |      - |      56 B |       0.004 |
```
