### ISSUE TITLE
Libdeflate as drop-in replacement for Zlib compression

### ISSUE THREAD

**Issue by stefanomerotta** [modernuo/ModernUO#1763]
This issue aims to track the replacement of Zlib with Libdeflate without method signature changes.

Ongoing development is on dedicated branch: [libdeflate](https://github.com/modernuo/ModernUO/tree/smerotta/libdeflate)

**Comment by stefanomerotta** [comment]
This is the first benchmark from the just created related branch on ModernUO-Benchmarks.
The gain in term of time is not so relevant: the other gain is the compress ratio that is a little better than Zlib.

I think that for that small bytearray (a fake gump in the benchmark) there is not a big difference between Zlib and Libdeflate.

BenchmarkDotNet v0.13.12, Windows 10 (10.0.19045.4355/22H2/2022Update) (Hyper-V)
11th Gen Intel Core i5-1145G7 2.60GHz, 1 CPU, 4 logical and 2 physical cores
.NET SDK 8.0.204
  [Host]   : .NET 8.0.4 (8.0.424.16909), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  .NET 8.0 : .NET 8.0.4 (8.0.424.16909), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

Job=.NET 8.0  Runtime=.NET 8.0

| Method         | Mean     | Error    | StdDev   | Allocated |
|--------------- |---------:|---------:|---------:|----------:|
| ZlibComp       | 21.68 us | 0.433 us | 0.635 us |         - |
| LibdeflateComp | 19.79 us | 0.385 us | 0.653 us |         - |

@kamronbatman could you pls check the benchmark in case I made a mistake?

**Comment by stefanomerotta** [comment]
This is the run of your latest rectified benchmark with some fixes in test method code

BenchmarkDotNet v0.13.12, Windows 10 (10.0.19045.4355/22H2/2022Update) (Hyper-V)
11th Gen Intel Core i5-1145G7 2.60GHz, 1 CPU, 4 logical and 2 physical cores
.NET SDK 8.0.205
  [Host]   : .NET 8.0.5 (8.0.524.21615), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  .NET 8.0 : .NET 8.0.5 (8.0.524.21615), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

Job=.NET 8.0  Runtime=.NET 8.0

| Method     | Mean     | Error    | StdDev   |
|----------- |---------:|---------:|---------:|
| LibDeflate | 19.48 us | 0.381 us | 0.581 us |
| Zlib       | 27.57 us | 0.545 us | 1.437 us |

**Comment by kamronbatman** [comment]
I like this!

Let's move forward. I'll clone the zlib.bindings repo and we can modify it to use libdeflate. Then replace the dependency/update readme in ModernUO.

**Comment by kamronbatman** [comment]
Fixed in #1774
