### ISSUE TITLE
Cannot buy from vendors, VendorBuyReply packet truncated

### ISSUE THREAD

**Issue by jabinb** [modernuo/ModernUO#182]
The client vendor buy reply packet is sent whenever a player purchases an item from an NPC vendor. However to the client nothing appears to happen once you finish buying from the vendor. I've narrowed down the issue to a packet handling problem.

The [`VendorBuyReply` ](https://github.com/modernuo/ModernUO/blob/master/Projects/Server/Network/PacketHandlers.cs#L498) packet handler requires the message size in order to read the list of items requested to be purchased:

```csharp
// PacketHandlers.cs#L500
      pvSrc.Seek(1, SeekOrigin.Begin);

      int msgSize = pvSrc.ReadUInt16();
      var vendor = World.FindMobile(pvSrc.ReadUInt32());
      var flag = pvSrc.ReadByte();

      if (vendor == null)
        return;
```
However at this point the message size has already been truncated by the main `ProcessPacket` function, which slices the packet after the final position containing the Packet Id and Packet Length:

```csharp
// PacketHandlers.cs#L350
      var packet = seq.Slice(r.Position);
      var memOwner = _memoryPool.Rent((int)packet.Length);

      packet.CopyTo(memOwner.Memory.Span);

      pump.QueueWork(ns, memOwner, handler.OnReceive);
```

The `VendorBuyReply` packet handler expects to receive *all* the packet data, however it's offset, so the msg size and serial are instead read out of the buy list data and come out all garbled. The information about the packet size doesn't seem to get preserved anywhere in the `PacketReader` to replace the `ReadUInt16` call from what I could see.

I would submit a PR however with the new packet updates coming and this not being a simple change I figured it would be best to raise it here.

I'm using a temporary workaround in `ProcessPacket`:

```csharp
// PacketHandlers.cs#L350
      if (packetId == 0x3B)
        r.Seek(0, SeekOrigin.Begin);
```

**Comment by kamronbatman** [comment]
Thanks Ill fix it in a little bit!
