### ISSUE TITLE
Unicode Conversion Issues During Build Process on Non-English Operating Systems

### ISSUE THREAD

**Issue by dckaratas** [modernuo/ModernUO#1996]
After the 'dotnet publish' step, in files like Server.VirtualHairInfo.v0 json, places containing the letter 'I' are converted to their Unicode equivalents when the operating system is not in English (in my case, Turkish). This causes an error during the build step. I tried changing the culture value in Main.cs and setting the language in publish.cmd, but these did not resolve the issue. The build was successful when the Windows language was set to English.

**Comment by kamronbatman** [comment]
Can you post an example of the text? This is handled by the schema generator, which we need to force to English I guess.

**Comment by Bohicatv** [comment]
The problem stems from how windows maps characters on windows 11 using different languages. Turkish has to be localized in runtime on his computer. Unless we can switch it based on detected system language. I don't know how to do this in .net 8+ without forcing all new compiles into Turkish "tr-TR".

**Comment by dckaratas** [comment]
Here an example in **Server.VirtualHairInfo.v0.json** file after build when windows language set to English

`{
      "name": "ItemId",
      "type": "int",
      "rule": "PrimitiveTypeMigrationRule",
      "ruleArguments": [
        ""
      ]
    }`
    
 when set to Turkish
 
 `{
      "name": "\u0130temId",
      "type": "int",
      "rule": "PrimitiveTypeMigrationRule",
      "ruleArguments": [
        ""
      ]
    }`

**Comment by kamronbatman** [comment]
I am hoping this gets resolved quickly so I don't have to switch CI/CD:
https://github.com/dotnet/roslyn/issues/75967#issuecomment-2494901036

**Comment by kamronbatman** [comment]
Update, the issue has been resolved by the Roslyn team. Waiting for a release of the library. The fix for this issue will be rolled into the .NET 9 upgrade.

**Comment by kamronbatman** [comment]
Should be fixed with #1984
