### ISSUE TITLE
Replace GetHashCode XOR

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#24]
The GetHashCode overrides that xor integer values are not actually a good idea. Not even sure if the values would be unique against the contents.

These should be replaced with prime number multiply-add.

**Comment by 3HMonkey** [comment]
Any references here or an example?


Code | File | Row | Column
-- | -- | -- | --
#region GetHashCode | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 167 | 15
public override int GetHashCode() => m_Address.GetHashCode(); | D:\github\ModernUO\Projects\Scripts\Accounting\Firewall.cs | 201 | 27
public override int GetHashCode() =>   m_CIDRPrefix.GetHashCode() ^ m_CIDRLength.GetHashCode(); | D:\github\ModernUO\Projects\Scripts\Accounting\Firewall.cs | 238 | 27
public override int GetHashCode() => m_Entry.GetHashCode(); | D:\github\ModernUO\Projects\Scripts\Accounting\Firewall.cs | 269 | 27
public override int GetHashCode() =>   Body.BodyID ^ (int)BodyType ^ Name.GetHashCode(); | D:\github\ModernUO\Projects\Scripts\Commands\Docs.cs | 2652 | 25
/*  name  */ "GetHashCode", | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 173 | 25
MethodInfo getHashCode =   active.GetMethod("GetHashCode", Type.EmptyTypes); | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 193 | 22
if (getHashCode == null) | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 195 | 15
getHashCode =   typeof(T).GetMethod("GetHashCode", Type.EmptyTypes); | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 196 | 13
emitter.Call(getHashCode); | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 220 | 28
emitter.Call(getHashCode); | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 228 | 28
"GetHashCode", | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 241 | 14
) ?? throw new Exception($"No   GetHashCode method found for type {typeof(T).FullName}") | D:\github\ModernUO\Projects\Scripts\Commands\Generic\Extensions\Compilers\DistinctCompiler.cs | 246 | 41
public override int GetHashCode() => BodyID.GetHashCode(); | D:\github\ModernUO\Projects\Server\Body.cs | 152 | 25
public override int GetHashCode() =>   Major ^ Minor ^ Revision ^ Patch ^ (int)Type; | D:\github\ModernUO\Projects\Server\ClientVersion.cs | 146 | 25
public override int GetHashCode() => m_X ^ m_Y; | D:\github\ModernUO\Projects\Server\Geometry.cs | 86 | 25
public override int GetHashCode() =>   m_X ^ m_Y ^ m_Z; | D:\github\ModernUO\Projects\Server\Geometry.cs | 172 | 25
public static int GetTypeID(Type type) =>   type?.FullName?.GetHashCode() ?? -1; | D:\github\ModernUO\Projects\Server\Gumps\Gump.cs | 162 | 63
AddHash(arguments.GetHashCode()); | D:\github\ModernUO\Projects\Server\ObjectPropertyList.cs | 119 | 25
public override int GetHashCode() => Value.GetHashCode(); | D:\github\ModernUO\Projects\Server\Serial.cs | 68 | 25

**Comment by kamronbatman** [comment]
```
public override int GetHashCode() => m_X ^ m_Y ^ m_Z;
```

**Comment by kamronbatman** [comment]
So it looks like xor is ok if it follow these rules:
1. Property values are not the same (0, 0, or 1, 1, or 100, 100)
1. Property values are never forward and backward at the same time during equality (a = 1, 0 and b = 0, 1)

My concern is with 
```csharp
public override int GetHashCode() => m_X ^ m_Y;
```
and
```csharp
public override int GetHashCode() => m_X ^ m_Y ^ m_Z;
```

Where X = 0, X = 0 and X = 1, X = 1 would be the same hash code.

**Comment by kamronbatman** [comment]
Per conversation with @jaedan, this isn't needed.
