### ISSUE TITLE
[dupe should not throw if duping an unsupported item

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#256]
Some items/mobs don't have empty ctors. Should send a message back explaining that instead of crashing.

As Vorspire suggested, [dupe can use the serial ctor and then replace properties using reflection.
There is a possible edge case where a normal ctor and deserialize (which wouldn't be called) does some initialization that is lost when using the serial ctor and copying properties.

**Comment by Vorspire** [comment]
You have to ensure that no arbitrary code ever runs in a deserialize method if that's the route you take.
This includes all custom implementations of Items that are not part of the distribution.
Instead I would recommend an audit of all types that inherit from Item, that do not have a default constructor, and implement a default constructor where appropriate.

**Comment by kamronbatman** [comment]
You are right that it is ultimately unsafe. On my shard Perilous I took great care to remove side effects and recursions. But as a distro we can't make those guarantees. It is MUCH faster than reflection though.
