### ISSUE TITLE
Nerdbank.GitVersioning error

### ISSUE THREAD

**Issue by rioux602** [modernuo/ModernUO#434]
I had to swtich Nerdbank.GitVersioning from 3.4.165-alpha to 3.3.37 because of a build error on Ubuntu 20.04

`~/.nuget/packages/nerdbank.gitversioning/3.4.165-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
~/.nuget/packages/nerdbank.gitversioning/3.4.165-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.ArgumentException: No git repo found here. (Parameter 'workingDirectory')
~/.nuget/packages/nerdbank.gitversioning/3.4.165-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
~/.nuget/packages/nerdbank.gitversioning/3.4.165-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
~/.nuget/packages/nerdbank.gitversioning/3.4.165-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()`

**Comment by kamronbatman** [comment]
I am surprised you got it to work with the current stable version. I had issues and was forced to upgrade to the alpha version. I'll look into it again and see if we can downgrade.

**Comment by kamronbatman** [comment]
The error indicates that you aren't using git. Did you download a release? I think there is an issue with releases since it isn't a git repo, so gitversioning can't infer what version it should be.

**Comment by kamronbatman** [comment]
Also @rioux602, looks like there is an issue with nuget, so testing will have to wait:
https://github.com/NuGet/Home/issues/10491

This probably affects Ubuntu 20LTS too.
