### ISSUE TITLE
INFO: Support Game Version

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#437]
hi, I wanted to know if you have a Discord server by any chance.
I wanted to know if there is a document where to find the list of commands.
What game versions does the server support?

**Comment by kamronbatman** [comment]
Hi @Arutosio, you can find us here: [ModernUO Discord](https://discord.com/invite/NUhe7Pq9gF)
I don't have a new docs system set up yet to get you a list of commands.
You can get a list of commands in-game by using `[help`

As for game versions, currently we support the game versions RunUO 2.7 supported (for now). This includes mechanics for some T2A, quite a bit of UOR (but not perfect), Pub 16, quite a bit of AOS (not perfect either), and some newer eras. RunUO stopped getting updates around UOML+ so lots of content is missing.

Primarily I am working on redoing the core, and encourage others to join to fix/update era mechanics, and add content/world building.

I'll be happy to help you out in further detail on discord!
