### ISSUE TITLE
Bad Error Message

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#438]
the first time it worked fine, then, I deleted all the contents of the Distribution folder.
I thought the code build recreated all files, i was to reset everything
![image](https://user-images.githubusercontent.com/30377429/106667029-aa3d7e80-65a8-11eb-81cf-fbb54428a391.png)
i fix it 
git checkout master ./Distribution

**Comment by kamronbatman** [comment]
Action item here is to fix the error messages for missing files.
