### ISSUE TITLE
Error with the original Client

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#450]
when i try to test the server with the original client v7.0.81.11
![image](https://user-images.githubusercontent.com/30377429/106937003-89e30080-671d-11eb-96f3-90a89b53b499.png)

**Comment by Arutosio** [comment]
File: Login.cfg> LoginServer = 127.0.0.1,2593
i tried to run client.exe inside the game directory

**Comment by 3HMonkey** [comment]
You need to run an assist like Razor/Steam or whatever to connect to the server.

**Comment by kamronbatman** [comment]
ModernUO does not support encrypted clients (yet). Sorry.
