### ISSUE TITLE
Crash sometimes on buy items on banker vendors

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#451]
when i buy this item on the banker run exception
![image](https://user-images.githubusercontent.com/30377429/106896680-33140180-66f2-11eb-8fbb-ceace095c053.png)

![image](https://user-images.githubusercontent.com/30377429/106896140-7a4dc280-66f1-11eb-806f-3963954c51b9.png)

**Comment by 3HMonkey** [comment]
A question, how much memory do you have?  Stackstrace shows insufficient memory error.

**Comment by kamronbatman** [comment]
That is a bad error. The packet ran out of buffer space. I need to fix it so it has a better description.

**Comment by Arutosio** [comment]
> A question, how much memory do you have? Stackstrace shows insufficient memory error.

i have 16Gb of Ram
