### ISSUE TITLE
Player Characters don't log out

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#452]
Characters sometimes don't disconnect, although it happens very rarely

**Comment by 3HMonkey** [comment]
Also in Inn? Can you please append more information to reproduce the problem? Thx

**Comment by kamronbatman** [comment]
Non-staff players don't log out right away unless they are at an inn. Can you double check if this is the case?

**Comment by Arutosio** [comment]
> Non-staff players don't log out right away unless they are at an inn. Can you double check if this is the case?

Ok let me check

**Comment by kamronbatman** [comment]
Closing this for now. Please reopen if you think it is a real issue.

**Comment by Arutosio** [comment]
ok
