### ISSUE TITLE
Error login / logout

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#459]
one of my friends can't log in, creating a new account ERROR:
![image](https://user-images.githubusercontent.com/30377429/106970028-54a1d700-674c-11eb-9ed2-20e7247fe5a9.png)

and another friend does not log out if the pg stays logged in
![image](https://user-images.githubusercontent.com/30377429/106970537-5f10a080-674d-11eb-9d53-ef7acf59569c.png)
maybe one of my friends used the "Get" button when he was logging out, maybe he bugged himself for this reason

these errors don't always happen, however, and understanding why is not easy

**Comment by kamronbatman** [comment]
I think this happens when the client abruptly disconnects. For example by closing the client, or presses the back arrow.
I think in Release this doesn't show up. I will be cleaning up the networking so this is easier to follow when it is an actual problem.

**Comment by kamronbatman** [comment]
Closing this for now. The messaging will be fixed soon.
