### ISSUE TITLE
Socket timeout exception (10060)

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#464]
sometimes when someone trains on the dummy, the server gives an error and disconnects the client from the server, the server throws this exception.

![image](https://user-images.githubusercontent.com/30377429/107068717-418d1680-67e1-11eb-8d09-762c92a51724.png)
![image](https://user-images.githubusercontent.com/30377429/107068633-26baa200-67e1-11eb-8f69-9136a0341cb4.png)

**Comment by kamronbatman** [comment]
@Arutosio a Socket 10060 is a timeout error. Do you know if the server froze? Also please test this against the newest `main` branch and see if you can replicate it.

Thanks!

**Comment by kamronbatman** [comment]
Per conversation with @Arutosio, looks like this isn't happening anymore.

**Comment by Arutosio** [comment]
I confirm, problem solved
