### ISSUE TITLE
Update string comparisons

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#50]
- [ ] Update string comparison (EndsWith etc) with Span handling.

**Comment by 3HMonkey** [comment]
BTW, here is s short summary about this: https://www.stevejgordon.co.uk/an-introduction-to-optimising-code-using-span-t

**Comment by kamronbatman** [comment]
I recommend making a StringUtils class in the core.

**Comment by kamronbatman** [comment]
This is related to #351
