### ISSUE TITLE
Disconecting on invalid Gump

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#507]
![image](https://user-images.githubusercontent.com/30377429/107622321-fac37480-6c57-11eb-89c2-d6d211e69b1f.png)
macrofile.macro:
```
!Loop
Assistant.Macros.DoubleClickTypeAction|4130|True
Assistant.Macros.PauseAction|00:00:03
Assistant.Macros.WaitForGumpAction|1599613558|False|300
Assistant.Macros.GumpResponseAction|4|0|0
Assistant.Macros.WaitForGumpAction|1599613558|False|300
```

**Comment by kamronbatman** [comment]
This is correct. What would you weather happens?

**Comment by Arutosio** [comment]
I was expecting a message telling me that I am trying to press a button from a gum that is not there.
without being disconnected

**Comment by Arutosio** [comment]
perfect, now I don't disconnect anymore
message server:
![image](https://user-images.githubusercontent.com/30377429/107950677-5c0c8000-6f97-11eb-9484-9283069472ea.png)

**Comment by kamronbatman** [comment]
I'll update the message to no longer say it is disconnecting
