### ISSUE TITLE
Add support for ZLib-IPP

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#51]
Add support for the Intel Performance Platform version of Zlib.
I am hesitant to use JTK's version because of reported issues.

If someone wants to optimize 1.2.8 or 1.2.11.1 with Intel IPP, that would be amazing!

**Comment by 3HMonkey** [comment]
Does that make sense? IPP is limited to Intel processors: https://software.intel.com/en-us/articles/intel-integrated-performance-primitives-intel-ipp-2019-system-requirements
