### ISSUE TITLE
Read only properties should not throw or allow modification in [props

### ISSUE THREAD

**Issue by Raaffaael** [modernuo/ModernUO#515]
the gump of the Metaltreasurechest trying to change the value of Totalgold TotalItems Totalweight a message appears on the client at the bottom left saying :(
an exception was caught, the ownership may not have changed)

**Comment by kamronbatman** [comment]
Thank you for reporting!
Can you attach a picture?
I also don't think you should be modifying total gold. That is a precomputed value.

**Comment by Raaffaael** [comment]
![Immagine 2021-02-23 161755](https://user-images.githubusercontent.com/79526297/108865125-2b5dc380-75f3-11eb-8546-dbcbccedfb78.png)

**Comment by malbolger** [comment]
In item.cs (around line 448) the read only bool needs added to the Command Properties.
`        [CommandProperty(AccessLevel.GameMaster)]
        public int TotalGold => GetTotal(TotalType.Gold);

        [CommandProperty(AccessLevel.GameMaster)]
        public int TotalItems => GetTotal(TotalType.Items);

        [CommandProperty(AccessLevel.GameMaster)]
        public int TotalWeight => GetTotal(TotalType.Weight);`

needs to be changed to:

`        [CommandProperty(AccessLevel.GameMaster, true)]
        public int TotalGold => GetTotal(TotalType.Gold);

        [CommandProperty(AccessLevel.GameMaster, true)]
        public int TotalItems => GetTotal(TotalType.Items);

        [CommandProperty(AccessLevel.GameMaster, true)]
        public int TotalWeight => GetTotal(TotalType.Weight);`

**Comment by kamronbatman** [comment]
It should detect that the property has no setter.

**Comment by malbolger** [comment]
I believe I found the issue. in PropsGump.cs (around line 232) 

`
                    if ((!prop.GetType().IsValueType || prop.CanWrite) && cpa != null &&
                        m_Mobile.AccessLevel >= cpa.WriteLevel && !cpa.ReadOnly)
`
the 'OR' needs to be 'AND' as it will always pass the check with !prop.GetType().IsValueType.

`
                    if ((!prop.GetType().IsValueType && prop.CanWrite) && cpa != null &&
                        m_Mobile.AccessLevel >= cpa.WriteLevel && !cpa.ReadOnly)
`

forgive me if this is not what you were asking for. I am quite new and just trying to help :)

**Comment by kamronbatman** [comment]
That looks good thanks. I'll make a PR to fix it!
