### ISSUE TITLE
[BUG] snapshot Failed

### ISSUE THREAD

**Issue by Raaffaael** [modernuo/ModernUO#523]
![image](https://user-images.githubusercontent.com/79526297/109325079-cd7ce600-7855-11eb-8980-9ea6f4c7d05b.png)

**Comment by kamronbatman** [comment]
I think windows doesn't like colons in the folder names. Thanks! I'll make a fix later today.

**Comment by karolswdev** [comment]
```csharp
public string ReplaceInvalidChars(string filename)
{
    return string.Join("_", filename.Split(Path.GetInvalidFileNameChars()));    
}
```

And you're set :)

**Comment by karolswdev** [comment]
> I think windows doesn't like colons in the folder names. Thanks! I'll make a fix later today.

want me to do a fix @kamronbatman, I have some capacity now.

**Comment by kamronbatman** [comment]
Since the invalid characters are due to GetTimestamp, let's just update that function. Please go for it and make a PR, thank you!

**Comment by kamronbatman** [comment]
> ```cs
> public string ReplaceInvalidChars(string filename)
> {
>     return string.Join("_", filename.Split(Path.GetInvalidFileNameChars()));    
> }
> ```
> 
> And you're set :)

Also fun fact, if you plan to replace an individual char with an individual char, it's better to find occurrences and replace them as a Span<char>. That way it can be done with zero memory allocation.

**Comment by Raaffaael** [comment]
thanks the serve works fine :)
