### ISSUE TITLE
Optimize Books

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#53]
While it seems trivial, this low hanging fruit should be straight forward.
Books are 20-40 pages and each one has an array of 40 page objects with empty line arrays.

Optimize this to use a linked list or at least an array of nulls. Could also pull from a pool of page objects to lower allocations.

This will also optimize the packets being sent.

**Comment by 3HMonkey** [comment]
So this is related to:

- D:\github\ModernUO\Projects\Scripts\Items\Books\BaseBook.cs
- D:\github\ModernUO\Projects\Scripts\Items\Books\Defined\BookContent.cs

Or did I miss something?

**Comment by kamronbatman** [comment]
Marking this as won't do. Books are not "hot" enough (they don't change enough) for this to matter.
