### ISSUE TITLE
[Bug] Fix boat movement and animation

### ISSUE THREAD

**Issue by immaciek** [modernuo/ModernUO#557]
- Boat elements keep moving independently while the boat is moving
- Due to this the player can stay in water while the boat swims away

https://drive.google.com/file/d/1NqBlgHHE9h53A8oUEpOnVSrp9dGzSESH/view?usp=sharing

**Comment by kamronbatman** [comment]
Related to this, various elements are out of alignment and don't move properly as the boat moves.
