### ISSUE TITLE
Client crashes when click on Virtues (Honesty for example)

### ISSUE THREAD

**Issue by 3HMonkey** [modernuo/ModernUO#562]
CUO-latest

![grafik](https://user-images.githubusercontent.com/4610892/113601034-2011a500-9641-11eb-834e-82b20375f671.png)
![grafik](https://user-images.githubusercontent.com/4610892/113601232-5a7b4200-9641-11eb-873c-729fefb750b7.png)

**Comment by karolswdev** [comment]
Wait. Can you talk about the specs of your computer? According to .NET you're running out of memory.

**Comment by kamronbatman** [comment]
That is not the case. The OOM is a network buffer issue. The network buffers are _static_ so they can run out of _space_ (not memory). I'll fix those exception messages soon.

Thank @3HMonkey, i'll look into this.
