### ISSUE TITLE
Mining Issue - Ore Amount

### ISSUE THREAD

**Issue by Lobstercraws** [modernuo/ModernUO#638]
When I try to mine ore using a pickaxe/shovel, after mining around 150-200 normal iron ore piles, I can only mine small piles weighing 2 stones regardless of where else I mine. 

This issue persists after restarting the server, waiting 24 hours, and trying different areas (Trammel, Fel, Malas, etc.)

An option or way to allow static ore locations instead of random locations for special ore would be awesome too!

![Mining Issue - Ore](https://user-images.githubusercontent.com/85316326/120710000-75680800-c472-11eb-94a6-47f4b2531888.jpg)

**Comment by kamronbatman** [comment]
Currently random ore is handled by an expansion flag. I can make a configuration for it too.

**Comment by Lobstercraws** [comment]
That would be awesome if you can, I would love to be able to make runebooks to all of the fancy ore locations again! I tried setting randomized veins to false but it didn't seem to have much effect.
