### ISSUE TITLE
Safe Logout Issue

### ISSUE THREAD

**Issue by Lobstercraws** [modernuo/ModernUO#639]
Inns are not functioning on my server (Base ModernUO, no mods), I have tried logging out at the New Haven inn, West Britain inn, and both Skara Brae inns. I was not in combat recently, or a criminal. Safe logout is working if I build a house and logout inside the house.

If I logout in an inn anywhere, I have to wait 5 minutes until timeout occurs.

**Comment by kamronbatman** [comment]
Fixed in #642
