### ISSUE TITLE
Wild Reagents - Can't Pick Up

### ISSUE THREAD

**Issue by Lobstercraws** [modernuo/ModernUO#640]
I am unable to pick up any wild reagents I find while running around. 

![Wild Reagents](https://user-images.githubusercontent.com/85316326/120710671-4900bb80-c473-11eb-8899-98dae5100fae.jpg)

**Comment by kamronbatman** [comment]
Probably a decoration.

**Comment by kamronbatman** [comment]
I couldn't replicate this. Closing now. @Lobstercraws if you want to send me your world file, I'll look into it more.
