### ISSUE TITLE
Bulk Order Deeds lose color after logout

### ISSUE THREAD

**Issue by Lobstercraws** [modernuo/ModernUO#641]
After logging out and restarting the server, all BODs appear to lose their color. This is affecting both blacksmithing and tailoring BODS.

![BOD Color Loss - Copy](https://user-images.githubusercontent.com/85316326/120710819-78afc380-c473-11eb-9cae-2c1942c3a84d.jpg)

**Comment by kamronbatman** [comment]
@Lobstercraws can you test PR 647 and see if it fixes your issue?
