### ISSUE TITLE
Build/Publish is not working on Windows systems

### ISSUE THREAD

**Issue by 3HMonkey** [modernuo/ModernUO#71]
Like the title says. Build is not working on Windows systems. Also publish is not copying the Assemblies to its output path.

**Comment by kamronbatman** [comment]
How are you publishing in windows? Is it Visual Studio or dotnet CLI or both?
Do you specify the windows profile?

Thanks for reporting!

**Comment by 3HMonkey** [comment]
I think that I meantioned multiple issues here:

- Build should work on all systems (Debug/Release) in addition to publishing. Currently it is working except copying the libs to the build path. (Visual Studio 2017/2019)
- On Windows systems `dotnet publish /p:PublishProfile=[platform][-SelfContained]` for example `dotnet publish /p:PublishProfile=Windows -SelfContained` is not working because `-SelfContained` is unknown. (Console)
- `dotnet publish /p:PublishProfile=Windows` does not copy "Data\Assemblies" to output path (Console)
- "Data" should be included in build/publish (if you clean your output folder, you'll be lost) (VS/Console)

**Comment by kamronbatman** [comment]
This was fixed in #72
