### ISSUE TITLE
Multiple House Customization/Sign bugs

### ISSUE THREAD

**Issue by Arthrutus** [modernuo/ModernUO#754]
- [ ] When customizing a house, placing a roof on the 2nd/3rd/4th floor becomes undeletable unless you are on the 1st floor.
- [ ] Tiles/walls/doors/roofs do not highlight red when the mouse is hovered over them for deletion.
- [ ] Customization menu is buggy and requires awkward mouse positioning to select an item. Sometimes multiple clicks are required for an item to be selected.

[NOT APPLICABLE] House sign menu does not display appropriate sentence on the INFORMATION page -> Missing "automatically" from "This house is ______________ refreshed." [NOT APPLICABLE]

**Comment by kamronbatman** [comment]
This was due to the Trammel client flag not being sent in.

**Comment by kamronbatman** [comment]
Looks like all of these are issues with CUO.
