### ISSUE TITLE
5.0.9.1 client not receiving appropriate message when lacking skill/mana for weapon specials

### ISSUE THREAD

**Issue by Arthrutus** [modernuo/ModernUO#755]
5.0.9.1 UO Client is not receiving appropriate "lack of skill" messages when attempting to utilize the primary or secondary weapon specials. If appropriate weapon skill is present, then the client will not receive appropriate "lack of mana" messages. 

- Note: 5.0.9.1 has appropriate Clilocs.

**Comment by kamronbatman** [comment]
This was also due to not sending the Trammel client flag.
