### ISSUE TITLE
Dragging items from paperdoll and dropping onto spellbook results in item dropping to floor

### ISSUE THREAD

**Issue by Arthrutus** [modernuo/ModernUO#767]
When unequipping anything from the paperdoll, dragging the item into the backpack and dropping it onto a spellbook/runebook will result in said item falling directly on the floor. 

According to OSI: Item should be returned to the last equipped position.

**Comment by kamronbatman** [comment]
Bounce issues hurt my brain. I wonder if this is an old RunUO bug or a new one.
