### ISSUE TITLE
Create actual logging

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#80]
- [ ] Use `Microsoft.Extensions.Logging` to create a logging system.

- [ ] Replace Console.WriteLine with Logging

**Comment by kamronbatman** [comment]
Serilog was also proposed by @deccer. Should investigate which gives the best performance given our needs.

**Comment by karolswdev** [comment]
I recommend using Serilog. The amount of Sinks you are able to use is insanely positive.
