### ISSUE TITLE
Doors are not in their places

### ISSUE THREAD

**Issue by romanlysenko** [modernuo/ModernUO#840]
![image](https://user-images.githubusercontent.com/58622888/141164260-d24ff124-9d0e-4d90-bebb-11565c6cc7cd.png)
![image](https://user-images.githubusercontent.com/58622888/141164273-97968f68-0dd6-4dbb-aff4-07e314e12440.png)

Correct coordinates:
![image](https://user-images.githubusercontent.com/58622888/141164467-e2255121-55f4-44a5-95c6-6b2c41087592.png)

**Comment by Arthrutus** [comment]
Ok it looks like those shouldn't be in the file. I will make a PR.
