### ISSUE TITLE
Wrong gender when creating a character

### ISSUE THREAD

**Issue by romanlysenko** [modernuo/ModernUO#852]
If you select the female gender in the character creation window, and then select the male gender again, then you will still have a character with a female gender.
![1](https://user-images.githubusercontent.com/58622888/141941951-d9bcde04-2f8c-4740-95d0-638836ce231c.png)

Why is the variable 'female' never updated?
![image](https://user-images.githubusercontent.com/58622888/141942390-2d36fc71-833c-471e-9861-fae21f013ebe.png)

**Comment by kamronbatman** [comment]
This was fixed on CUO.
