### ISSUE TITLE
BaseWeapon damage bonus should be 0 for default WeaponDamageLevel

### ISSUE THREAD

**Issue by SpeedyDevil** [modernuo/ModernUO#884]
https://github.com/modernuo/ModernUO/blob/aba34730308a0eb957601ddd300e96f0aaf115a5/Projects/UOContent/Items/Weapons/BaseWeapon.cs#L2414

This should be 0 for default. Now when you have exceptional weapon, it double adds 20 in default case.

**Comment by kamronbatman** [comment]
Great catch, thanks!
