### ISSUE TITLE
[Implement] Integrate objects into the house

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#924]
![image](https://user-images.githubusercontent.com/30377429/152400807-a14b41b2-4767-457b-9ebc-efb96b570b1f.png)
I suggest adding a way to make objects part of a classic house.
in order to add walls and doors, the added doors must have the possibility to set the level of security like those present on the house.
and when the house is demolished it eliminates the objects added later.
or alternatively make the classic house editable.

**Comment by Arthrutus** [comment]
This is a heavily custom idea and not one integrated by OSI standards. One could simply utilize the customizable house option and design a classic house, proceeding to add optional walls, doors, etc. Simply adding the option to customize current classic houses would require a lot of work.

**Comment by kamronbatman** [comment]
This isn't really possible because classic houses use mutli files. You would need an Ultima Live type of feature, and it would only be compatible with CUO.
