### ISSUE TITLE
Crash: Wepoll Handle not initialized error

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#926]
![image](https://user-images.githubusercontent.com/30377429/152571007-f77b5f5a-c587-46ea-bb7a-e77b619234ed.png)
before crashing a user logged in with an old version of the game

**Comment by Arthrutus** [comment]
Did you confirm that your server is not restricting older UO clients? As it stands, the default result is that clients older than the client you used to establish the server will not be allowed to access.

**Comment by kamronbatman** [comment]
It's a crash in the NetState handle, which can only happen if there is a race condition or a bug in WePoll so I need to build better debugging for the nuget package.
