### ISSUE TITLE
[Enhancement] Management permissions to lock down and secure

### ISSUE THREAD

**Issue by Arutosio** [modernuo/ModernUO#927]
it would be very helpful if co-owners, friends and guild members can lock down and secure the containers with their security level but without the possibility to change the secure
![image](https://user-images.githubusercontent.com/30377429/152791107-03315380-6e71-4db4-97bf-5f84e345ab19.png)

it would also be very useful for the owner to have a section where he can enable and disable the permissions of co-owner friends and guild to lock down and secure containers inside this gump.
![image](https://user-images.githubusercontent.com/30377429/152791163-10cbfa5b-ba7e-4970-a7c1-e47d314ae484.png)

what do you think about this?
I think it would be a revolution for the guilds

**Comment by Raaffaael** [comment]
Yes. I think it's a good idea

**Comment by kamronbatman** [comment]
I agree in general. Does OSI have any of these features for any of it's eras? I haven't decided if I want to support non-OSI features.

Thoughts?

**Comment by Arthrutus** [comment]
https://uo.com/wiki/ultima-online-wiki/gameplay/houses-placing-a-house/house-ownership-4-managing-your-home/

The link here leading to uo.com explains more. Friends of the house can lock down containers and items. Co-Owners of the house can secure containers and items.

**Comment by Arutosio** [comment]
> https://uo.com/wiki/ultima-online-wiki/gameplay/houses-placing-a-house/house-ownership-4-managing-your-home/
> 
> The link here leading to uo.com explains more. Friends of the house can lock down containers and items. Co-Owners of the house can secure containers and items.

fantastic, hope the whole management system is implemented soon

**Comment by fabrizioiacobucci** [comment]
> I agree in general. Does OSI have any of these features for any of it's eras? I haven't decided if I want to support non-OSI features.
> 
> Thoughts?

In general, would it makes sense to standardize MUO only to OSI features and leave the non-OSI per Shard customization?

**Comment by kamronbatman** [comment]
Yeah I agree. We can add options/features if they aren't invasive. Otherwise maybe add them to a github repo or our discord forum.
