### ISSUE TITLE
Update MailKit 3.1.0 -> 3.1.1

### ISSUE THREAD

**Issue by Mink80** [modernuo/ModernUO#956]

**Comment by 3HMonkey** [comment]
+1

**Comment by kamronbatman** [comment]
It already is:

https://github.com/modernuo/ModernUO/blob/60991b7ab05a49ff17c385e08e6daa57ae5fbc7e/Projects/UOContent/UOContent.csproj#L41

Please post the error you are getting.

**Comment by Mink80** [comment]
![image](https://user-images.githubusercontent.com/46659983/157764072-14204b6a-2999-4f45-b14c-03bf327c159a.png)

It still wants to have 3.1.0 for some reason :(

**Comment by kamronbatman** [comment]
That is misleading. The minor/build versions don't report, so it is still referencing 3.1.1. I wonder why the file can't be found. I can't replicate this problem locally. 🤔

**Comment by kamronbatman** [comment]
For anyone that is stumbling on this, the issue is that modernuo.json `"assemblies"` path is pointing to the wrong path.
